baseURL = "https://nicklanng.github.io/"
title = "i do web stuff"
copyright = "Copyright (c) 2018, all rights reserved."
canonifyurls = true
languageCode = "en-US"
paginate = 5
theme = "hugo-dusk"

googleAnalytics = ""
disqusShortname = ""

[author]
  name = "nicklanng"

SectionPagesMenu = "main"

# use Chroma for syntax highlight
pygmentsStyle = "native" # other dark style options: vim, fruity, monokai
# enable syntax highlight for code blocks
pygmentsCodeFences = true

[[menu.main]]
  name = "Posts"
  weight = -120
  identifier = "post"
  url = "/post/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[params.meta]
  keywords = "blog, tech, go, web"
  description = "i do web stuff."

[params]
  github = "nicklanng"
  twitter = "nicklanng"
  email = "rinse@rinseworld.com"

[params.colors]
  # hugo-dusk colors
  background = "#101010" # background color for the site
  main = "#6699cc"
  text = "#dbdbdb"
  code-quote-bg = "#1D1F21" # background color for quotes and code blocks
  copyright = "#404040" # copyright text color
